export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const CHANGE_DAILY_PRACTICES = 'CHANGE_DAILY_PRACTICES';
export const CHANGE_EXAM_DATE = 'CHANGE_EXAM_DATE';
export const SET_START_DAY = 'SET_START_DAY';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';