// auth
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const CHANGE_DAILY_PRACTICES = 'CHANGE_DAILY_PRACTICES';
export const CHANGE_EXAM_DATE = 'CHANGE_EXAM_DATE';
export const SET_START_DAY = 'SET_START_DAY';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';

// notification
export const SET_NOTIFICATION_TIME = 'SET_NOTIFICATION_TIME';
export const CHECK_NOTIFICATION = 'CHECK_NOTIFICATION';

// dic
export const DIC_SAVE_WORD = 'DIC_SAVE_WORD';
export const DIC_UNSAVE_WORD = 'DIC_UNSAVE_WORD';

// question
export const SAVE_QUESTION = 'SAVE_QUESTION';
export const UNSAVE_QUESTION = 'UNSAVE_QUESTION';
export const GET_RESULT = 'GET_RESULT';
export const SET_NOT_FINISHED = 'SET_NOT_FINISHED';

export const DO_QUESTION = 'DO_QUESTION';